// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4CovNErGTEpR3Mk8JAA3uhcPtJ86oGcQ',
    appId: '1:326773378862:web:7994cea75862cd5fc5f4bf',
    messagingSenderId: '326773378862',
    projectId: 'doit-example',
    authDomain: 'doit-example.firebaseapp.com',
    storageBucket: 'doit-example.appspot.com',
    measurementId: 'G-V5Q1QZDJ8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp3YniBK47yIDOoene-uXdMWIXqBUk3U0',
    appId: '1:326773378862:android:14909b10f6281280c5f4bf',
    messagingSenderId: '326773378862',
    projectId: 'doit-example',
    storageBucket: 'doit-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx_AiXy259BR9Q3VROB4x6rgJ9IXeX9VY',
    appId: '1:326773378862:ios:66755bb656f5c168c5f4bf',
    messagingSenderId: '326773378862',
    projectId: 'doit-example',
    storageBucket: 'doit-example.appspot.com',
    iosClientId:
        '326773378862-2166npj8fivat2ulhf1gqhaq5de4rk89.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDoitFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx_AiXy259BR9Q3VROB4x6rgJ9IXeX9VY',
    appId: '1:326773378862:ios:66755bb656f5c168c5f4bf',
    messagingSenderId: '326773378862',
    projectId: 'doit-example',
    storageBucket: 'doit-example.appspot.com',
    iosClientId:
        '326773378862-2166npj8fivat2ulhf1gqhaq5de4rk89.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDoitFirebase',
  );
}
